//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllGreatFilms.BusinessObjectLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class movie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public movie()
        {
            this.movie_quotes = new HashSet<movie_quotes>();
            this.ratings = new HashSet<rating>();
            this.awards = new HashSet<award>();
            this.actors = new HashSet<actor>();
            this.genres = new HashSet<genre>();
            this.moods = new HashSet<mood>();
            this.users = new HashSet<user>();
            this.users1 = new HashSet<user>();
            this.user_watched_movies = new HashSet<user_watched_movies>();
        }
    
        public int movie_id { get; set; }
        public string title { get; set; }
        public string poster { get; set; }
        public int language { get; set; }
        public int country { get; set; }
        public string duration { get; set; }
        public System.DateTime year { get; set; }
        public int director { get; set; }
        public int writer { get; set; }
        public string Youtube { get; set; }
        public string imdb { get; set; }
        public string rottenTomatoes { get; set; }
        public string netflix { get; set; }
        public System.DateTime dateAdded { get; set; }
        public string synopsis { get; set; }
        public string agfReview { get; set; }
    
        public virtual country country1 { get; set; }
        public virtual director director1 { get; set; }
        public virtual language language1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<movie_quotes> movie_quotes { get; set; }
        public virtual writer writer1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rating> ratings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<award> awards { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<actor> actors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<genre> genres { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mood> moods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<user> users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<user> users1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<user_watched_movies> user_watched_movies { get; set; }
    }
}
