//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllGreatFilms.BusinessObjectLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class rating
    {
        public int rating_id { get; set; }
        public int movie_id { get; set; }
        public decimal user_rating { get; set; }
        public string review { get; set; }
        public Nullable<decimal> agf_rating { get; set; }
        public System.Guid reviewer_id { get; set; }
        public Nullable<decimal> imdbR { get; set; }
        public Nullable<decimal> rottenR { get; set; }
        public Nullable<decimal> metaR { get; set; }
    
        public virtual movie movie { get; set; }
        public virtual user user { get; set; }
    }
}
